/**
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.validation;

import org.poc.idm.xtext.wdl.validation.AbstractWdlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WdlValidator extends AbstractWdlValidator {
}
