/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WdlRuntimeModule extends org.poc.idm.xtext.wdl.AbstractWdlRuntimeModule {

}
