/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WdlStandaloneSetup extends WdlStandaloneSetupGenerated{

	public static void doSetup() {
		new WdlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

