/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WdlUiModule extends org.poc.idm.xtext.wdl.ui.AbstractWdlUiModule {
	public WdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
