/**
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.serializer;

import org.poc.idm.xtext.wdl.serializer.AbstractWdlSyntacticSequencer;

@SuppressWarnings("all")
public class WdlSyntacticSequencer extends AbstractWdlSyntacticSequencer {
}
