/**
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.serializer;

import org.poc.idm.xtext.wdl.serializer.AbstractWdlSemanticSequencer;

@SuppressWarnings("all")
public class WdlSemanticSequencer extends AbstractWdlSemanticSequencer {
}
