/**
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.ui.contentassist;

import org.poc.idm.xtext.wdl.ui.contentassist.AbstractWdlProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WdlProposalProvider extends AbstractWdlProposalProvider {
}
