/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.poc.idm.xtext.wdl.ui.internal.WdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WdlActivator.getInstance().getInjector(WdlActivator.ORG_POC_IDM_XTEXT_WDL_WDL);
	}
	
}
