/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WdlUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.poc.idm.xtext.wdl.ui.internal.WdlActivator.getInstance().getInjector("org.poc.idm.xtext.wdl.Wdl");
	}
	
}
