/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.poc.idm.xtext.wdl.services.WdlGrammarAccess;

public class WdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private WdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.poc.idm.xtext.wdl.parser.antlr.internal.InternalWdlParser createParser(XtextTokenStream stream) {
		return new org.poc.idm.xtext.wdl.parser.antlr.internal.InternalWdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "WebsiteRule";
	}
	
	public WdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
