/*
 * generated by Xtext
 */
grammar InternalWdl;

options {
	superClass=AbstractInternalContentAssistParser;
	
}

@lexer::header {
package org.poc.idm.xtext.wdl.ui.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.poc.idm.xtext.wdl.ui.contentassist.antlr.internal; 

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.DFA;
import org.poc.idm.xtext.wdl.services.WdlGrammarAccess;

}

@parser::members {
 
 	private WdlGrammarAccess grammarAccess;
 	
    public void setGrammarAccess(WdlGrammarAccess grammarAccess) {
    	this.grammarAccess = grammarAccess;
    }
    
    @Override
    protected Grammar getGrammar() {
    	return grammarAccess.getGrammar();
    }
    
    @Override
    protected String getValueForTokenName(String tokenName) {
    	return tokenName;
    }

}




// Entry rule entryRuleWebsiteRule
entryRuleWebsiteRule 
:
{ before(grammarAccess.getWebsiteRuleRule()); }
	 ruleWebsiteRule
{ after(grammarAccess.getWebsiteRuleRule()); } 
	 EOF 
;

// Rule WebsiteRule
ruleWebsiteRule
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getWebsiteRuleAccess().getGroup()); }
(rule__WebsiteRule__Group__0)
{ after(grammarAccess.getWebsiteRuleAccess().getGroup()); }
)

;
finally {
	restoreStackSize(stackSize);
}



// Entry rule entryRulePageRule
entryRulePageRule 
:
{ before(grammarAccess.getPageRuleRule()); }
	 rulePageRule
{ after(grammarAccess.getPageRuleRule()); } 
	 EOF 
;

// Rule PageRule
rulePageRule
    @init {
		int stackSize = keepStackSize();
    }
	:
(
{ before(grammarAccess.getPageRuleAccess().getGroup()); }
(rule__PageRule__Group__0)
{ after(grammarAccess.getPageRuleAccess().getGroup()); }
)

;
finally {
	restoreStackSize(stackSize);
}






rule__WebsiteRule__Group__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group__0__Impl
	rule__WebsiteRule__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getIsMobileFriendlyAssignment_0()); }
(rule__WebsiteRule__IsMobileFriendlyAssignment_0)?
{ after(grammarAccess.getWebsiteRuleAccess().getIsMobileFriendlyAssignment_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__WebsiteRule__Group__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group__1__Impl
	rule__WebsiteRule__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getWebsiteKeyword_1()); }

	'website' 

{ after(grammarAccess.getWebsiteRuleAccess().getWebsiteKeyword_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__WebsiteRule__Group__2
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group__2__Impl
	rule__WebsiteRule__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group__2__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getLeftCurlyBracketKeyword_2()); }

	'{' 

{ after(grammarAccess.getWebsiteRuleAccess().getLeftCurlyBracketKeyword_2()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__WebsiteRule__Group__3
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group__3__Impl
	rule__WebsiteRule__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group__3__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getGroup_3()); }
(rule__WebsiteRule__Group_3__0)?
{ after(grammarAccess.getWebsiteRuleAccess().getGroup_3()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__WebsiteRule__Group__4
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group__4__Impl
	rule__WebsiteRule__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group__4__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
(
{ before(grammarAccess.getWebsiteRuleAccess().getPagesAssignment_4()); }
(rule__WebsiteRule__PagesAssignment_4)
{ after(grammarAccess.getWebsiteRuleAccess().getPagesAssignment_4()); }
)
(
{ before(grammarAccess.getWebsiteRuleAccess().getPagesAssignment_4()); }
(rule__WebsiteRule__PagesAssignment_4)*
{ after(grammarAccess.getWebsiteRuleAccess().getPagesAssignment_4()); }
)
)

;
finally {
	restoreStackSize(stackSize);
}


rule__WebsiteRule__Group__5
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group__5__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group__5__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getRightCurlyBracketKeyword_5()); }

	'}' 

{ after(grammarAccess.getWebsiteRuleAccess().getRightCurlyBracketKeyword_5()); }
)

;
finally {
	restoreStackSize(stackSize);
}














rule__WebsiteRule__Group_3__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group_3__0__Impl
	rule__WebsiteRule__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group_3__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getCopyrightKeyword_3_0()); }

	'copyright :' 

{ after(grammarAccess.getWebsiteRuleAccess().getCopyrightKeyword_3_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__WebsiteRule__Group_3__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__WebsiteRule__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__Group_3__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getCopyrightAssignment_3_1()); }
(rule__WebsiteRule__CopyrightAssignment_3_1)
{ after(grammarAccess.getWebsiteRuleAccess().getCopyrightAssignment_3_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}






rule__PageRule__Group__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__0__Impl
	rule__PageRule__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getPageKeyword_0()); }

	'page' 

{ after(grammarAccess.getPageRuleAccess().getPageKeyword_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__1__Impl
	rule__PageRule__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getNameAssignment_1()); }
(rule__PageRule__NameAssignment_1)
{ after(grammarAccess.getPageRuleAccess().getNameAssignment_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group__2
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__2__Impl
	rule__PageRule__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__2__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getLeftCurlyBracketKeyword_2()); }

	'{' 

{ after(grammarAccess.getPageRuleAccess().getLeftCurlyBracketKeyword_2()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group__3
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__3__Impl
	rule__PageRule__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__3__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTitleKeyword_3()); }

	'title : ' 

{ after(grammarAccess.getPageRuleAccess().getTitleKeyword_3()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group__4
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__4__Impl
	rule__PageRule__Group__5
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__4__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTitleAssignment_4()); }
(rule__PageRule__TitleAssignment_4)
{ after(grammarAccess.getPageRuleAccess().getTitleAssignment_4()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group__5
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__5__Impl
	rule__PageRule__Group__6
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__5__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getGroup_5()); }
(rule__PageRule__Group_5__0)?
{ after(grammarAccess.getPageRuleAccess().getGroup_5()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group__6
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group__6__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group__6__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getRightCurlyBracketKeyword_6()); }

	'}' 

{ after(grammarAccess.getPageRuleAccess().getRightCurlyBracketKeyword_6()); }
)

;
finally {
	restoreStackSize(stackSize);
}
















rule__PageRule__Group_5__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group_5__0__Impl
	rule__PageRule__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group_5__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getMenuKeyword_5_0()); }

	'menu :' 

{ after(grammarAccess.getPageRuleAccess().getMenuKeyword_5_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group_5__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group_5__1__Impl
	rule__PageRule__Group_5__2
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group_5__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTargetsAssignment_5_1()); }
(rule__PageRule__TargetsAssignment_5_1)
{ after(grammarAccess.getPageRuleAccess().getTargetsAssignment_5_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group_5__2
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group_5__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group_5__2__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getGroup_5_2()); }
(rule__PageRule__Group_5_2__0)*
{ after(grammarAccess.getPageRuleAccess().getGroup_5_2()); }
)

;
finally {
	restoreStackSize(stackSize);
}








rule__PageRule__Group_5_2__0
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group_5_2__0__Impl
	rule__PageRule__Group_5_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group_5_2__0__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getCommaKeyword_5_2_0()); }

	',' 

{ after(grammarAccess.getPageRuleAccess().getCommaKeyword_5_2_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


rule__PageRule__Group_5_2__1
    @init {
		int stackSize = keepStackSize();
    }
:
	rule__PageRule__Group_5_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__Group_5_2__1__Impl
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTargetsAssignment_5_2_1()); }
(rule__PageRule__TargetsAssignment_5_2_1)
{ after(grammarAccess.getPageRuleAccess().getTargetsAssignment_5_2_1()); }
)

;
finally {
	restoreStackSize(stackSize);
}







rule__WebsiteRule__IsMobileFriendlyAssignment_0
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getIsMobileFriendlyMobileKeyword_0_0()); }
(
{ before(grammarAccess.getWebsiteRuleAccess().getIsMobileFriendlyMobileKeyword_0_0()); }

	'mobile' 

{ after(grammarAccess.getWebsiteRuleAccess().getIsMobileFriendlyMobileKeyword_0_0()); }
)

{ after(grammarAccess.getWebsiteRuleAccess().getIsMobileFriendlyMobileKeyword_0_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__CopyrightAssignment_3_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getCopyrightSTRINGTerminalRuleCall_3_1_0()); }
	RULE_STRING{ after(grammarAccess.getWebsiteRuleAccess().getCopyrightSTRINGTerminalRuleCall_3_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__WebsiteRule__PagesAssignment_4
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getWebsiteRuleAccess().getPagesPageRuleParserRuleCall_4_0()); }
	rulePageRule{ after(grammarAccess.getWebsiteRuleAccess().getPagesPageRuleParserRuleCall_4_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__NameAssignment_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getNameIDTerminalRuleCall_1_0()); }
	RULE_ID{ after(grammarAccess.getPageRuleAccess().getNameIDTerminalRuleCall_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__TitleAssignment_4
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTitleSTRINGTerminalRuleCall_4_0()); }
	RULE_STRING{ after(grammarAccess.getPageRuleAccess().getTitleSTRINGTerminalRuleCall_4_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__TargetsAssignment_5_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTargetsPageCrossReference_5_1_0()); }
(
{ before(grammarAccess.getPageRuleAccess().getTargetsPageIDTerminalRuleCall_5_1_0_1()); }
	RULE_ID{ after(grammarAccess.getPageRuleAccess().getTargetsPageIDTerminalRuleCall_5_1_0_1()); }
)
{ after(grammarAccess.getPageRuleAccess().getTargetsPageCrossReference_5_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}

rule__PageRule__TargetsAssignment_5_2_1
    @init {
		int stackSize = keepStackSize();
    }
:
(
{ before(grammarAccess.getPageRuleAccess().getTargetsPageCrossReference_5_2_1_0()); }
(
{ before(grammarAccess.getPageRuleAccess().getTargetsPageIDTerminalRuleCall_5_2_1_0_1()); }
	RULE_ID{ after(grammarAccess.getPageRuleAccess().getTargetsPageIDTerminalRuleCall_5_2_1_0_1()); }
)
{ after(grammarAccess.getPageRuleAccess().getTargetsPageCrossReference_5_2_1_0()); }
)

;
finally {
	restoreStackSize(stackSize);
}


RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;


