/*
 * generated by Xtext
 */
package org.poc.idm.xtext.wdl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class WdlGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class WebsiteRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WebsiteRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsMobileFriendlyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsMobileFriendlyMobileKeyword_0_0 = (Keyword)cIsMobileFriendlyAssignment_0.eContents().get(0);
		private final Keyword cWebsiteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCopyrightKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCopyrightAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCopyrightSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cCopyrightAssignment_3_1.eContents().get(0);
		private final Assignment cPagesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPagesPageRuleParserRuleCall_4_0 = (RuleCall)cPagesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//WebsiteRule returns Website:
		//	isMobileFriendly?="mobile"? "website" "{" ("copyright :" copyright=STRING)? pages+=PageRule+ "}";
		@Override public ParserRule getRule() { return rule; }

		//isMobileFriendly?="mobile"? "website" "{" ("copyright :" copyright=STRING)? pages+=PageRule+ "}"
		public Group getGroup() { return cGroup; }

		//isMobileFriendly?="mobile"?
		public Assignment getIsMobileFriendlyAssignment_0() { return cIsMobileFriendlyAssignment_0; }

		//"mobile"
		public Keyword getIsMobileFriendlyMobileKeyword_0_0() { return cIsMobileFriendlyMobileKeyword_0_0; }

		//"website"
		public Keyword getWebsiteKeyword_1() { return cWebsiteKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("copyright :" copyright=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"copyright :"
		public Keyword getCopyrightKeyword_3_0() { return cCopyrightKeyword_3_0; }

		//copyright=STRING
		public Assignment getCopyrightAssignment_3_1() { return cCopyrightAssignment_3_1; }

		//STRING
		public RuleCall getCopyrightSTRINGTerminalRuleCall_3_1_0() { return cCopyrightSTRINGTerminalRuleCall_3_1_0; }

		//pages+=PageRule+
		public Assignment getPagesAssignment_4() { return cPagesAssignment_4; }

		//PageRule
		public RuleCall getPagesPageRuleParserRuleCall_4_0() { return cPagesPageRuleParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PageRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PageRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTitleKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTitleAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTitleSTRINGTerminalRuleCall_4_0 = (RuleCall)cTitleAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cMenuKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTargetsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cTargetsPageCrossReference_5_1_0 = (CrossReference)cTargetsAssignment_5_1.eContents().get(0);
		private final RuleCall cTargetsPageIDTerminalRuleCall_5_1_0_1 = (RuleCall)cTargetsPageCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cTargetsAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final CrossReference cTargetsPageCrossReference_5_2_1_0 = (CrossReference)cTargetsAssignment_5_2_1.eContents().get(0);
		private final RuleCall cTargetsPageIDTerminalRuleCall_5_2_1_0_1 = (RuleCall)cTargetsPageCrossReference_5_2_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//PageRule returns Page:
		//	"page" name=ID "{" "title : " title=STRING ("menu :" targets+=[Page] ("," targets+=[Page])*)? "}";
		@Override public ParserRule getRule() { return rule; }

		//"page" name=ID "{" "title : " title=STRING ("menu :" targets+=[Page] ("," targets+=[Page])*)? "}"
		public Group getGroup() { return cGroup; }

		//"page"
		public Keyword getPageKeyword_0() { return cPageKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"title : "
		public Keyword getTitleKeyword_3() { return cTitleKeyword_3; }

		//title=STRING
		public Assignment getTitleAssignment_4() { return cTitleAssignment_4; }

		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_4_0() { return cTitleSTRINGTerminalRuleCall_4_0; }

		//("menu :" targets+=[Page] ("," targets+=[Page])*)?
		public Group getGroup_5() { return cGroup_5; }

		//"menu :"
		public Keyword getMenuKeyword_5_0() { return cMenuKeyword_5_0; }

		//targets+=[Page]
		public Assignment getTargetsAssignment_5_1() { return cTargetsAssignment_5_1; }

		//[Page]
		public CrossReference getTargetsPageCrossReference_5_1_0() { return cTargetsPageCrossReference_5_1_0; }

		//ID
		public RuleCall getTargetsPageIDTerminalRuleCall_5_1_0_1() { return cTargetsPageIDTerminalRuleCall_5_1_0_1; }

		//("," targets+=[Page])*
		public Group getGroup_5_2() { return cGroup_5_2; }

		//","
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }

		//targets+=[Page]
		public Assignment getTargetsAssignment_5_2_1() { return cTargetsAssignment_5_2_1; }

		//[Page]
		public CrossReference getTargetsPageCrossReference_5_2_1_0() { return cTargetsPageCrossReference_5_2_1_0; }

		//ID
		public RuleCall getTargetsPageIDTerminalRuleCall_5_2_1_0_1() { return cTargetsPageIDTerminalRuleCall_5_2_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final WebsiteRuleElements pWebsiteRule;
	private final PageRuleElements pPageRule;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public WdlGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pWebsiteRule = new WebsiteRuleElements();
		this.pPageRule = new PageRuleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.poc.idm.xtext.wdl.Wdl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//WebsiteRule returns Website:
	//	isMobileFriendly?="mobile"? "website" "{" ("copyright :" copyright=STRING)? pages+=PageRule+ "}";
	public WebsiteRuleElements getWebsiteRuleAccess() {
		return pWebsiteRule;
	}
	
	public ParserRule getWebsiteRuleRule() {
		return getWebsiteRuleAccess().getRule();
	}

	//PageRule returns Page:
	//	"page" name=ID "{" "title : " title=STRING ("menu :" targets+=[Page] ("," targets+=[Page])*)? "}";
	public PageRuleElements getPageRuleAccess() {
		return pPageRule;
	}
	
	public ParserRule getPageRuleRule() {
		return getPageRuleAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
